version: '3.7'

services:
  redis:
    image: redis/redis-stack:6.2.6-v7
    container_name: ms_simulator_redis
    environment:
      REDIS_ARGS: "--appendonly yes --aof-use-rdb-preamble yes"
    networks:
      - ms_simulator
    ports:
      - "8001:8001"
      - "6379:6379"
    volumes:
      - ms_simulator_redis:/data

networks:
  ms_simulator:
    external: true

volumes:
  ms_simulator_redis:
    external: true